### ISSUE TITLE
Rp番号の表現法への検討

### ISSUE THREAD

**Issue by skoba** [jami-fhir-jp-wg/swg5#1]

**Comment by tmskmr** [comment]
児玉さんのサンプルでは現状 identifierには配列で以下のように「オーダーID」と「オーダーID_RP番号」をセットしていますが、RP番号を表現するのにこれでよいか議論が必要だと思います。
>         "identifier": [
>          {
>            "system": "OID:1.2.392.100495.20.3.11",
>            "value": "12345678"
>          },
>          {
>            "system": "OID:1.2.392.100495.20.3.81",
>            "value": "12345678_01"
>          }
>        ],

**Comment by skoba** [comment]
これはおそらくbundleを使わずに各薬剤をMedicationRequestで送信する場合には処方箋IDとRPIDがセットでないといけなかったのではないかなと思います。
オーダーIDとは別にDosage.sequenceが妥当かなとも思います。

**Comment by skoba** [comment]
groupIdentifierを候補とする。

**Comment by skoba** [comment]
groupIdentifierで記述する
