### ISSUE TITLE
1回量と1日量の表現方法についての検討

### ISSUE THREAD

**Issue by skoba** [jami-fhir-jp-wg/swg5#2]
1回量がどれで、1日量がどれかの区別がつかない。

**Comment by tmskmr** [comment]
児玉さんのサンプルでは、現状doseAndRate属性に以下のように配列で１回量と１日量をセットしていますが、これだとどちらが１回量でどちらが１日量かコードの意味を理解しないと区別できません。コードの意味が分からなくても最低限の情報は読み取れるようにした方がよいと思います。
>              "doseAndRate": [
>               {
>                 "type": {
>                   "coding": [
>                     {
>                       "system": "LC",
>                       "code": "Give Amount - Minimum",
>                       "display": "与薬量－最小"
>                     }
>                   ]
>                 },
>                 "doseQuantity": {
>                   "value": 1,
>                   "unit": "錠",
>                   "code": "TAB"
>                 }
>               },
>               {
>                 "type": {
>                   "coding": [
>                     {
>                       "system": "LC",
>                       "code": "Total Daily Dose",
>                       "display": "1 日あたりの総投与量"
>                     }
>                   ]
>                 },
>                 "doseQuantity": {
>                   "value": 3,
>                   "unit": "錠",
>                   "code": "TAB"
>                 }
>               }
>             ]
>           }
>         ],
>

**Comment by Acedia-Belphegor** [comment]
反応遅くなり申し訳ございません。
以下のサンプルを作成してみました。

- 1日量 (v2: RXE-19) を `extensions` に切り出す (urlは仮)
- 1回量 (v2: RXE-3) は従来通り `doseAndRate` のまま (typeは消す)

```
"dosageInstruction": [
    {
        "extension": [
            {
                // RXE-19.1日あたりの総投与量
                "url": "http://hl7fhir.jp/fhir/StructureDefinition/Extension-JPCore-TotalDailyDose",
                "valueQuantity": {
                    "value": 3,
                    "unit": "錠",
                    "code": "TAB"
                }
            }
        ],
        "text": "内服・経口・１日３回朝昼夕食後",
        "additionalInstruction": [
            {
                "coding": [
                    {
                        "system": "JHSP0005",
                        "code": "01",
                        "display": "１回目から服用"
                    }
                ]
            }
        ],
        "timing": {
            "event": [
                "2016-08-25T00:00:00+00:00"
            ],
            "repeat": {
                "period": 3
            },
            "code": [
                {
                    "coding": [
                    {
                        "system": "JAMISDP01",
                        "code": "1013044400000000",
                        "display": "内服・経口・１日３回朝昼夕食後"
                    }
                    ]
                }
            ]
        },
        "route": {
            "coding": [
                {
                    "system": "HL70162",
                    "code": "PO",
                    "display": "口"
                }
            ]
        },        
        "doseAndRate": [
            {
                // RXE-3.与薬量－最小
                "doseQuantity": {
                    "value": 1,
                    "unit": "錠",
                    "code": "TAB"
                }
            }
        ]
    }
]
```

**Comment by skoba** [comment]
原則1回量とするが、1日量 x doseRatioの組み合わせで表現する方法も検討する。
