### ISSUE TITLE
入外区分や処方区分の表現方法

### ISSUE THREAD

**Issue by skoba** [jami-fhir-jp-wg/swg5#3]
HL7表＋JHSP表かmedicationrequest-categoryか

**Comment by tmskmr** [comment]
児玉さんのサンプルでは、以下のようにcategory属性でHL7表やJHSP表を使用して入外区分や処方区分、用法種別を表現していますが、FHIRのデフォルトバインディングのmedicationrequest-category (inpatient , outpatient, community, discharge) は入外区分の代わりに使うことができそうです。それ以外の処方区分、用法種別の表現方法についてもこれでよいか検討が必要だと思います。
>         "category": [
>           {
>             "coding": [
>               {
>                 "system": "HL70482",
>                 "code": "O",
>                 "display": "外来患者オーダ"
>               }
>             ]
>           },
>           {
>             "coding": [
>               {
>                 "system": "MR9P",
>                 "code": "OHP",
>                 "display": "外来処方"
>               }
>             ]
>           },
>           {
>             "coding": [
>               {
>                 "system": "MR9P",
>                 "code": "OHI",
>                 "display": "院内処方"
>               }
>             ]
>           },
>           {
>             "coding": [
>               {
>                 "system": "JHSP0003",
>                 "code": "21",
>                 "display": "内服"
>               }
>             ]
>           }
>         ],
>

**Comment by skoba** [comment]
持参薬の区分がないので、「JAHIS処方データ規約V3.0Cに記載されているMERIT-9処方オーダ表7」に従うのが良いかなと思います。

**Comment by skoba** [comment]
JAHIS処方データ規約V3.0Cに記載されているMERIT-9処方オーダ表7 ＋　
https://www.hl7.org/fhir/valueset-medicationrequest-category.html

**Comment by skoba** [comment]
categoryには処方区分としてJAHIS処方データ規約V3.0Cに記載されているMERIT-9 MR9P表を使用する。JP_Extensionとして、レセプト処方区分（JHSP003)表を加える。
