### ISSUE TITLE
MedicationRequest.dosageInstruction.textの内容

### ISSUE THREAD

**Issue by skoba** [jami-fhir-jp-wg/swg5#4]
用法だけでよいか、開始日・日数・コメント等を含めるか

**Comment by tmskmr** [comment]
児玉さんのサンプルでは、以下のように dosageInstruction.text に標準用法コードの名称のみをセットしていますが、処方箋イメージが再現できる程度の情報は含めてはどうでしょうか。少なくとも、dosageInstructionで表現している情報は含めた方がよいと思います。
>         "dosageInstruction": [
>           {
>             "text": "内服・経口・１日３回朝昼夕食後",
>             "additionalInstruction": [
>               {
>                 "coding": [
>                   {
>                     "system": "JHSP0005",
>                     "code": "01",
>                     "display": "１回目から服用"
>                   }
>                 ]
>               }
>             ],
> 

処方箋イメージとしては例えば以下のようなテキストです。
> Rp1 ムコダイン錠２５０ｍｇ                １錠 （１日３錠）
> 　　パンスポリンＴ錠１００　１００ｍｇ      ２錠 （１日６錠）
> 　　2020/2/4 から１日３回朝昼夕食後  ３日分
> 
> Pp2 アレピアチン１０％                   ５０ｍｇ（１日１００ｍｇ）
> 　　フェノバルビタール散１０％「ホエイ」    ５０ｍｇ（１日１００ｍｇ）
>　　2020/2/4 から １日２回朝夕食後    １４日分

**Comment by skoba** [comment]
Textとして処方箋が再現できるイメージを書くのは、その上位のMedicationRequest.textのほうがいいかなと思います。

参考：
https://www.hl7.org/fhir/medicationrequest0301.json.html

**Comment by skoba** [comment]
ただし、textはあくまで補助情報で人間可読であってもそのまま表示されるわけでもないので、他の表現が正規化されていれば重要ではないと考えますが、正規化が難しいのでMML4の処方箋モジュールはテキスト形式のみにしたんだっけ。

**Comment by skoba** [comment]
MedicationRequest.textはxhtmlでないといけない

**Comment by skoba** [comment]
MedicationRequest.note.textも候補とする

**Comment by skoba** [comment]
dosageInstruction.textとしては、コード化されていない用法を記述するのに用いる。

**Comment by skoba** [comment]
必要であれば下記のように

<xhtml>Rp1 ムコダイン錠２５０ｍｇ １錠 （１日３錠）
　　パンスポリンＴ錠１００　１００ｍｇ ２錠 （１日６錠）
　　2020/2/4 から１日３回朝昼夕食後 ３日分

Pp2 アレピアチン１０％ ５０ｍｇ（１日１００ｍｇ）
　　フェノバルビタール散１０％「ホエイ」 ５０ｍｇ（１日１００ｍｇ）
　　2020/2/4 から １日２回朝夕食後 １４日分</xhtml>
