### ISSUE TITLE
剤型の表現方法

### ISSUE THREAD

**Issue by skoba** [jami-fhir-jp-wg/swg5#5]
medicationCodeableConceptだと表現できないのでmedicationReference.formを使用するか

**Comment by tmskmr** [comment]
上記の通りですが、児玉さんのサンプルでは、以下のようにcategoryを使って表現しているようです。いずれにしても、表現する・しない、表現するとしたらどの方法にするか、を検討すべきと思います。

>         "category": [
>           {
>             "coding": [
>               {
>                 "system": "HL70482",
>                 "code": "O",
>                 "display": "外来患者オーダ"
>               }
>             ]
>           },
>           {
>             "coding": [
>               {
>                 "system": "MR9P",
>                 "code": "PWD",
>                 "display": "散剤"
>               }
>             ]
>           },
>

**Comment by skoba** [comment]
薬剤名称・コードには剤形情報が含まれていはいます。
ただ、剤形情報は用法・用量、調剤にもつながるので、表現は必要と考えます。
Medication.formあるいはcategoryのいずれかでしょうか。

**Comment by skoba** [comment]
containedでみていく

**Comment by skoba** [comment]
基本的に剤型はここに書くのは不要ということにします。
