### ISSUE TITLE
依頼医（処方医）の記述ポイント

### ISSUE THREAD

**Issue by skoba** [jami-fhir-jp-wg/swg5#6]
MedicationRequest.requester and/or Practitioner

**Comment by tmskmr** [comment]
児玉さんのサンプルでは、下記のように MedicationRequestリソースの前に Practionerリソースを置いて依頼医を記述していますが、MedicationRequest.requester は使えないでしょうか。
>     {
>       "resource": {
>         "id": "0",
>         "identifier": [
>           {
>             "system": "OID:1.2.392.100495.20.3.41.1",
>             "value": "123456"
>           }
>         ],
>         "name": [
>           {
>             "extension": [
>               {
>                 "url": "http://hl7.org/fhir/StructureDefinition/iso21090-EN-representation",
>                 "valueCode": "IDE"
>               }
>             ],
>             "family": "医師",
>             "given": [
>               "春子"
>             ]
>           },
>           {
>             "extension": [
>               {
>                 "url": "http://hl7.org/fhir/StructureDefinition/iso21090-EN-representation",
>                 "valueCode": "SYL"
>               }
>             ],
>             "family": "イシ",
>             "given": [
>               "ハルコ"
>             ]
>           }
>         ],
>         "resourceType": "Practitioner"
>       }
>     },
>

**Comment by Acedia-Belphegor** [comment]
`MedicationRequest.requester` は、他リソースの参照(Reference)になっていますので、同Bundle内のPractitionerの `id` を設定する形式では如何でしょうか？

下記の例では、処方医を表現するPractitionerのid `95e89727-6e35-4c7e-8a26-7238c7804271` を、MedicationRequest.requesterに設定しております。(idの付番ルールは仮)

### Practitioner

```
    {
      "resource": {
        "id": "95e89727-6e35-4c7e-8a26-7238c7804271",
        "identifier": [
          {
            "system": "OID:1.2.392.100495.20.3.41.1",
            "value": "123456"
          }
        ],
        "name": [
          {
            "extension": [
              {
                "url": "http://hl7.org/fhir/StructureDefinition/iso21090-EN-representation",
                "valueCode": "IDE"
              }
            ],
            "family": "医師",
            "given": [
              "春子"
            ]
          },
          {
            "extension": [
              {
                "url": "http://hl7.org/fhir/StructureDefinition/iso21090-EN-representation",
                "valueCode": "SYL"
              }
            ],
            "family": "イシ",
            "given": [
              "ハルコ"
            ]
          }
        ],
        "resourceType": "Practitioner"
      }
    },
```

### MedicationRequest (部分的に抜粋)

```
    {
      "resource": {
        "id": "a81ce4a0-0052-40c7-9d85-3844a9a67aed",

 -- (中略) --

        "requester": {
          "id": "95e89727-6e35-4c7e-8a26-7238c7804271",
          "type": "Practitioner"
        },

 -- (中略) --

        "resourceType": "MedicationRequest"
      }
    },
```

**Comment by tmskmr** [comment]
contained 属性を使ってPractitionerリソースをMedicationRequestリソースの中で記述してはどうでしょうか。

**Comment by skoba** [comment]
あまり繰り返しが冗長にならないようにしたいと思っておりますが、PractitionerのID付番ルールをどうするかなども検討事項でしょうか。

**Comment by skoba** [comment]
resourceのidを参照することに

**Comment by skoba** [comment]
bundle内のresourceについてidentifierを使って参照
