### ISSUE TITLE
頓用条件

### ISSUE THREAD

**Issue by skoba** [jami-fhir-jp-wg/swg5#7]
dosageInstruction.timing.code or asNeededCodeableConcept

**Comment by tmskmr** [comment]
児玉さんのサンプルでは、以下のように dosageInstruction.timing.code を使用していますが、dosageInstruction.asNeededCodeableConcept でも表現できるのではないか、どちらかというと頓用条件はそちらの方が適切なのではないか、という話です。

>         "dosageInstruction": [
>           {
>             "text": "内服・経口・疼痛時",
>             "patientInstruction": "1 日2 回まで",
>             "timing": {
>               "event": [
>                 "2016-08-25T00:00:00+00:00"
>               ],
>               "repeat": {
>                 "period": 10,
>                 "periodUnit": "回"
>               },
>               "code": [
>                 {
>                   "coding": [
>                     {
>                       "system": "JAMISDP01",
>                       "code": "1050110020000000",
>                       "display": "内服・経口・疼痛時"
>                     }
>                   ]
>                 }
>               ]
>             },
>

**Comment by skoba** [comment]
確かに、屯用指示の例ではasNeededCodeableConcept指示となっていますね。
      "patientInstruction": "Take one to two tablets every four to six hours as needed for rib pain",
      "timing": {
        "repeat": {
          "frequency": 1,
          "period": 4,
          "periodMax": 6,
          "periodUnit": "h"
        }
      },
      "asNeededCodeableConcept": {
        "coding": [
          {
            "system": "http://snomed.info/sct",
            "code": "297217002",
            "display": "Rib Pain (finding)"
          }
        ]
      },


https://www.hl7.org/fhir/medicationrequest0301.json.html

**Comment by Acedia-Belphegor** [comment]
`asNeededCodeableConcept` を使用するように変更したverです。

```
"dosageInstruction": [
    {
    "text": "内服・経口・疼痛時",
    "patientInstruction": "1 日2 回まで",
    "timing": {
        "event": [
        "2016-08-25T00:00:00+00:00"
        ],
        "repeat": {
        "period": 10,
        "periodUnit": "回"
        }
    },
    "asNeededCodeableConcept": {
        "coding": [
        {
            "system": "JAMISDP01",
            "code": "1050110020000000",
            "display": "内服・経口・疼痛時"
        }
        ]
    },
    "route": {
        "coding": [
        {
            "system": "HL70162",
            "code": "PO",
            "display": "口"
        }
        ]
    },
    "doseAndRate": [
        {
        "doseQuantity": {
            "value": 1,
            "unit": "錠",
            "code": "TAB"
        }
        }
    ]
    }
]
```

**Comment by Acedia-Belphegor** [comment]
しかしながら、頓用の場合のみ用法の格納場所が異なるのも、受け取り側にとっては処理が煩雑になることも懸念されますので、頓用の場合は `asNeededBoolean: true` をセットするverも作成してみましたが如何でしょうか？

```
"dosageInstruction": [
    {
    "text": "内服・経口・疼痛時",
    "patientInstruction": "1 日2 回まで",
    "timing": {
        "event": [
        "2016-08-25T00:00:00+00:00"
        ],
        "repeat": {
        "period": 10,
        "periodUnit": "回"
        },
        "code": [
        {
            "coding": [
            {
                "system": "JAMISDP01",
                "code": "1050110020000000",
                "display": "内服・経口・疼痛時"
            }
            ]
        }
        ]
    },
    "asNeededBoolean": true,  # 頓用
    "route": {
        "coding": [
        {
            "system": "HL70162",
            "code": "PO",
            "display": "口"
        }
        ]
    },
    "doseAndRate": [
        {
        "doseQuantity": {
            "value": 1,
            "unit": "錠",
            "code": "TAB"
        }
        }
    ]
    }
]
```

**Comment by skoba** [comment]
日本の処方箋だと頓用処方と定期内服処方では処方区分が異なります。
用法区分も異なるので、asNeededCodeableConceptでもあまり混乱はないと思います。

**Comment by skoba** [comment]
asNeededBooleanでフラグ立てる

**Comment by skoba** [comment]
Medication.doseInstruction.timingで頓用条件を示し、頓用フラグをasNeededCodeableConceptに記入する。
