### ISSUE TITLE
不均等投与の表現方法

### ISSUE THREAD

**Issue by skoba** [jami-fhir-jp-wg/swg5#9]
処方・注射標準用法規格 and/or １回量ごとにMedicationRequestを繰り返す

**Comment by tmskmr** [comment]
児玉さんのサンプルでは、各タイミングの用量を以下のように dosageInstruction.additionalInstruction にセットしていますが、コードの意味が分からないと正しく理解できないので、冗長ですがタイミングごとにMedicalRequestを繰り返すという考え方もありそうです。

>         "dosageInstruction": [
>           {
>             "text": "内服・経口・１日３回朝昼夕食後",
>             "additionalInstruction": [
>               {
>                 "coding": [
>                   {
>                     "system": "JAMISDP01",
>                     "code": "V14NNNNN",
>                     "display": "４錠"
>                   }
>                 ]
>               },
>               {
>                 "coding": [
>                   {
>                     "system": "JAMISDP01",
>                     "code": "V22NNNNN",
>                     "display": "２錠"
>                   }
>                 ]
>               },
>               {
>                 "coding": [
>                   {
>                     "system": "JAMISDP01",
>                     "code": "V31NNNNN",
>                     "display": "１錠"
>                   }
>                 ]
>               }
>             ],
>

**Comment by skoba** [comment]
Dosage.sequenceで一日の順番をつけておくのが無難

**Comment by yoshinori-kodama** [comment]
## example.1

[imbalance_1.txt](https://github.com/jami-fhir-jp-wg/swg5/files/4391027/imbalance_1.txt)

### 処方せん表記の参考例
```
Rp01 プレドニン錠５ｍｇ         朝4錠、昼2錠、夕方1錠（１日７錠）
    　１日３回朝昼夕食後        ７日分
```

### 説明
- `dosageInstruction` を不均等回数分繰り返す
- `sequence` で投与順番を設定する
- `doseAndRate` に1回分の投与量を設定する

### 懸念
- 「１日３回朝昼夕食後」を記述する場所が `MedicationRequest.note` くらいしかない
- timing.event(服用開始日) / timing.repeat(投与日数) / route(投与経路) などが冗長になる
- １日量をどこに記述するか？

**Comment by yoshinori-kodama** [comment]
## example.2

[imbalance_2.txt](https://github.com/jami-fhir-jp-wg/swg5/files/4391306/imbalance_2.txt)

### 処方せん表記の参考例（example.1と同じ）
```
Rp01 プレドニン錠５ｍｇ         朝4錠、昼2錠、夕方1錠（１日７錠）
    　１日３回朝昼夕食後        ７日分
```

### 説明
- sequence=0に「１日３回朝昼夕食後」、1日量、冗長になる項目を記述する

### 懸念
- アドホックな感じが否めない

**Comment by yoshinori-kodama** [comment]
## example.3

[imbalance_3.txt](https://github.com/jami-fhir-jp-wg/swg5/files/4391309/imbalance_3.txt)

### 処方せん表記の参考例（example.1と同じ）
```
Rp01 プレドニン錠５ｍｇ         朝4錠、昼2錠、夕方1錠（１日７錠）
    　１日３回朝昼夕食後        ７日分
```

### 説明
- `dosageInstruction` の全体を繰り返すのではなく、 `dosageInstruction.doseAndRate` を繰り返す

### 懸念
- 不均等処方であるか否かを判別する区分が無い（doseAndRateが繰り返されているかで判断？）

**Comment by skoba** [comment]
Dosageを繰り返し、extensionで順番(sequence)を示す。
